config/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views import defaults as default_views

from wenhu.news.views import NewsListView

urlpatterns = [
                  path('', NewsListView.as_view(), name='home'),

                  # 用户管理
                  path('users/', include('wenhu.users.urls', namespace='users')),
                  path('accounts/', include('allauth.urls')),

                  # 第三方应用
                  path('markdownx/', include('markdownx.urls')),
                  path('comments/', include('django_comments.urls')),
                  path('search/', include('haystack.urls')),

                  #  开发的应用
                  path('news/', include('wenhu.news.urls', namespace='news')),
                  path('articles/', include('wenhu.articles.urls', namespace='articles')),
                  path('qa/', include('wenhu.qa.urls', namespace='qa')),
                  path('messages/', include('wenhu.messager.urls', namespace='messages')),
                  path('notifications/', include('wenhu.notifications.urls', namespace='notifications')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # DEBUG=True的时候可以调试出错页面
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

wenhu/news/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.urls import path

from wenhu.news import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='list'),
    path('post-news/', views.post_news, name='post_news'),
    path('delete/<pk>/', views.NewsDeleteView.as_view(), name='delete_news'),
    path('like/', views.like, name='like_post'),
    path('get-thread/', views.get_thread, name='get_thread'),
    path('post-comment/', views.post_comment, name='post_comments'),
    path('update-interactions/', views.update_interactions, name='update_interactions'),
]

wenhu/qa/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-

from django.urls import path

from wenhu.qa import views

app_name = 'qa'

urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name='unanswered_q'),
    path('answered/', views.AnsweredQuestionListView.as_view(), name='answered_q'),
    path('indexed/', views.QuestionListView.as_view(), name='all_q'),
    path('ask-question/', views.CreateQuestionView.as_view(), name='ask_question'),
    path('question-detail/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('propose-answer/<int:question_id>/', views.CreateAnswerView.as_view(), name='propose_answer'),
    path('question/vote/', views.question_vote, name='question_vote'),
    path('answer/vote/', views.answer_vote, name='answer_vote'),
    path('accept-answer/', views.accept_answer, name='accept_answer'),
]

wenhu/users/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.urls import path

from wenhu.users import views

app_name = "users"
urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

wenhu/articles/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from django_comments.signals import comment_was_posted

from wenhu.articles.models import Article
from wenhu.articles.forms import ArticleForm
from wenhu.helpers import AuthorRequiredMixin
from wenhu.notifications.views import notification_handler


class ArticlesListView(LoginRequiredMixin, ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 20
    context_object_name = "articles"
    template_name = "articles/article_list.html"  # 可省略

    def get_context_data(self, *args, **kwargs):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """草稿箱文章列表"""

    def get_queryset(self, **kwargs):
        # 当前用户的草稿
        return Article.objects.filter(user=self.request.user).get_drafts()


@method_decorator(cache_page(60 * 60), name='get')
class CreateArticleView(LoginRequiredMixin, CreateView):
    """创建文章"""
    model = Article
    message = "您的文章已创建成功！"  # Django框架中的消息机制
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateArticleView, self).form_valid(form)

    def get_success_url(self):
        """创建成功后跳转"""
        messages.success(self.request, self.message)  # 消息传递给下一次请求
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, DetailView):
    """文章详情"""
    model = Article
    template_name = 'articles/article_detail.html'

    def get_queryset(self):
        return Article.objects.select_related('user').filter(slug=self.kwargs['slug'])


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):  # 注意类的继承顺序
    """编辑文章"""
    model = Article
    message = "您的文章编辑成功！"
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(EditArticleView, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


def notify_comment(**kwargs):
    """文章有评论时通知作者"""
    actor = kwargs['request'].user
    obj = kwargs['comment'].content_object

    notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)

wenhu/messager/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from asgiref.sync import async_to_sync
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.template.loader import render_to_string

from channels.layers import get_channel_layer

from wenhu.messager.models import Message
from wenhu.helpers import ajax_required


class MessagesListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = "messager/message_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MessagesListView, self).get_context_data()
        # 获取除当前登录用户外的所有用户，按最近登录时间降序排列
        context['users_list'] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user
        ).order_by('-last_login')[:10]
        # 最近一次私信互动的用户
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(self.request.user, active_user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_object_or_404(get_user_model(),
                                        username=self.kwargs["username"])
        return Message.objects.get_conversation(self.request.user, active_user)


@login_required
@ajax_required
@require_http_methods(["POST"])
def send_message(request):
    """发送消息，AJAX POST请求"""
    sender = request.user
    recipient_username = request.POST['to']
    recipient = get_user_model().objects.get(username=recipient_username)
    message = request.POST['message']
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(
            sender=sender,
            recipient=recipient,
            message=message
        )

        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            'message': render_to_string('messager/single_message.html', {"message": msg}),
            'sender': sender.username
        }
        # group_send(group: 所在组-接收者的username, message: 消息内容)
        async_to_sync(channel_layer.group_send)(recipient.username, payload)

        return render(request, 'messager/single_message.html', {'message': msg})

    return HttpResponse()

wenhu/news/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DeleteView

from wenhu.helpers import ajax_required, AuthorRequiredMixin
from wenhu.news.models import News


class NewsListView(LoginRequiredMixin, ListView):
    """首页动态"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self, **kwargs):
        return News.objects.filter(reply=False).select_related('user', 'parent').prefetch_related('liked')


class NewsDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    """继承DeleteView重写delete方法，使用AJAX响应请求"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy("news:list")  # 在项目的URLConf未加载前使用


@login_required
@ajax_required
@require_http_methods(["POST"])
def post_news(request):
    """发送动态，AJAX POST请求"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(["POST"])
def like(request):
    """点赞，AJAX POST请求"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    # 取消或者添加赞
    news.switch_like(request.user)
    # 返回赞的数量
    return JsonResponse({"likes": news.count_likers()})


@login_required
@ajax_required
@require_http_methods(["GET"])
def get_thread(request):
    """返回动态的评论，AJAX GET请求"""
    news_id = request.GET['news']
    news = News.objects.select_related('user').get(pk=news_id)  # 不是.get(pk=news_id).select_related('user')
    # render_to_string()表示加载模板，填充数据，返回字符串
    news_html = render_to_string("news/news_single.html", {"news": news})  # 没有评论的时候
    thread_html = render_to_string("news/news_thread.html", {"thread": news.get_thread()})  # 有评论的时候
    return JsonResponse({
        "uuid": news_id,
        "news": news_html,
        "thread": thread_html,
    })


@login_required
@ajax_required
@require_http_methods(["POST"])
def post_comment(request):
    """评论，AJAX POST请求"""
    post = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    parent = News.objects.get(pk=parent_id)
    if post:
        parent.reply_this(request.user, post)
        return JsonResponse({'comments': parent.comment_count()})
    else:  # 评论为空返回400.html
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(["POST"])
def update_interactions(request):
    """更新互动信息"""
    data_point = request.POST['id_value']
    news = News.objects.get(pk=data_point)
    return JsonResponse({'likes': news.count_likers(), 'comments': news.comment_count()})

wenhu/notifications/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView

from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

from wenhu.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """未读通知列表"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    """将所有通知标为已读"""
    request.user.notifications.mark_all_as_read()
    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'用户{request.user.username}的所有通知标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug):
    """根据slug标为已读"""
    notification = get_object_or_404(Notification, slug=slug)
    notification.mark_as_read()

    redirect_url = request.GET.get('next')

    messages.add_message(request, messages.SUCCESS, f'通知{notification}标为已读')

    if redirect_url:
        return redirect(redirect_url)

    return redirect('notifications:unread')


@login_required
def get_latest_notifications(request):
    """最近的未读通知"""
    notifications = request.user.notifications.get_most_recent()
    return render(request, 'notifications/most_recent.html',
                  {'notifications': notifications})


def notification_handler(actor, recipient, verb, action_object, **kwargs):
    """
    通知处理器
    :param actor:           request.user对象
    :param recipient:       User Instance 接收者实例，可以是一个或者多个接收者
    :param verb:            str 通知类别
    :param action_object:   Instance 动作对象的实例
    :param kwargs:          key, id_value等
    :return:                None
    """
    if actor.username != recipient.username and recipient.username == action_object.user.username:
        # 只通知接收者，即recipient == 动作对象的作者
        key = kwargs.get('key', 'notification')
        id_value = kwargs.get('id_value', None)
        # 记录通知内容
        Notification.objects.create(
            actor=actor,
            recipient=recipient,
            verb=verb,
            action_object=action_object
        )

        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            'key': key,
            'actor_name': actor.username,
            'id_value': id_value
        }
        async_to_sync(channel_layer.group_send)('notifications', payload)

wenhu/users/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView

from wenhu.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/user_detail.html'
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user.username)
        context['moments_num'] = user.publisher.filter(reply=False).count()  # 'publisher'为News表中的related_name
        context['article_num'] = user.author.filter(status='P').count()  # 只算已发表的文章
        context['comment_num'] = user.publisher.filter(reply=True).count() + user.comment_comments.all().count()  # 动态+文章的评论数
        context['question_num'] = user.q_author.all().count()
        context['answer_num'] = user.a_author.all().count()

        # 互动数 = 动态点赞数+问答点赞数+评论数+私信用户数(双方都有发送和接收私信)
        tmp = set()
        # 我发送私信给了多少不同的用户
        sent_num = user.sent_messages.all()
        for s in sent_num:
            tmp.add(s.recipient.username)
        # 我接收的所有私信来自多少不同的用户
        received_num = user.received_messages.all()
        for r in received_num:
            tmp.add(r.sender.username)

        context['interaction_num'] = user.liked_news.all().count() + user.qa_vote.all().count() + \
                                     context['comment_num'] + len(tmp)

        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """用户只能更新自己的信息"""

    model = User
    fields = ['nickname', 'email', 'picture', 'introduction', 'job_title', 'location',
              'personal_url', 'weibo', 'zhihu', 'github', 'linkedin']

    template_name = 'users/user_form.html'

    def get_success_url(self):
        """更新成功后跳转到用户自己的页面"""
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, queryset=None):
        return self.request.user

wenhu/templates/qa/answer_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}回答问题 - {{ block.super }}{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'qa:all_q' %}">问答</a></li>
            <li class="breadcrumb-item active" aria-current="page">回答问题</li>
        </ol>
    </nav>
    <form action="{% url 'qa:propose_answer' view.kwargs.question_id %}" id="answerForm" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button id="answer" type="submit" class="btn btn-primary">回答</button>
            <a class="btn btn-light" style="float:right" href="{% url 'qa:all_q' %}">取消</a>

        </div>
    </form>
    {{ form.media }}

{% endblock content %}

wenhu/templates/qa/answer_sample.html
{% load static humanize thumbnail %}

<div class="row answer" answer-id="{{ answer.uuid_id }}">
    {% csrf_token %}
    <div class="col-md-1 options">
        <i class="fa fa-chevron-up vote up-vote answer-vote {% if request.user in answer.get_upvoters %}voted{% endif %}" aria-hidden="true"
           title="单击赞同，再次点击取消"></i>
        <span id="answerVotes" class="votes">{{ answer.total_votes }}</span>
        <i class="fa fa-chevron-down vote down-vote answer-vote {% if request.user in answer.get_downvoters %}voted{% endif %}" aria-hidden="true"
           title="单击反对，再次点击取消"></i>
        <!--自己提的问题显示是否接受回答的按钮-->
        {% if answer.is_answer %}
            <i class="fa fa-check accept accepted" aria-hidden="true" title="此回答已被采纳"></i>
        {% elif not answer.is_answer and user.username == question.user.username %}
            <i id="acceptAnswer" class="fa fa-check accept" aria-hidden="true" title="点击采纳回答"></i>
        {% endif %}
    </div>
    <div class="col-md-11">
        <div class="answer-user">
            <div class="profile-picture">
                {% thumbnail answer.user.picture "x50" as im %}
                    <img src="{{ im.url }}" class="user-image" style="border-radius: 50%;" alt="用户头像">
                {% empty %}
                    <img src="{% static 'img/user.png' %}" class="pull-left" height="50px" alt="没有头像"/>
                {% endthumbnail %}
                <a href="{% url 'users:detail' answer.user.username %}" class="username">{{ answer.user.get_profile_name }}</a>
                <small class="answered">回答于 {{ answer.created_at|naturaltime }}</small>
            </div>
        </div>
        <div class="answer-description">
            {{ answer.get_markdown|safe }}
        </div>
    </div>
</div>
<hr>

wenhu/templates/qa/question_detail.html
{% extends 'base.html' %}
{% load static humanize %}

{% block title %}{{ question.title }}{% endblock %}

{% block css %}
    <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'qa:unanswered_q' %}">问答</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ question.title }}</li>
        </ol>
    </nav>
    <div class="page-header">
        <a href="{% url 'qa:ask_question' %}" class="btn btn-primary pull-right">
            <i class="fa fa-pencil" aria-hidden="true"></i> 提问
        </a>
        <h4>{{ question.title }}</h4>
    </div>
    <div class="row question" question-id="{{ question.id }}">
        <div class="col-md-1">
            <div class="question-info options">
                <h3 class="{% if question.has_answer %}bg-success text-white{% endif %}">{{ question.count_answers }}</h3>
                <small class="text-secondary">回答</small>
                <i id="questionUpVote" class="fa fa-chevron-up vote up-vote question-vote{% if request.user in question.get_upvoters %} vote
                d{% endif %}"
                   aria-hidden="true" title="单击赞同，再次点击取消"></i>
                <h3 id="questionVotes">{{ question.total_votes }}</h3>
                <i id="questionDownVote" class="fa fa-chevron-down vote down-vote question-vote{% if request.user in question.get_downvoters %} voted
{% endif %}" aria-hidden="true" title="单击反对，再次点击取消"></i>
                <small class="text-secondary">投票</small>
            </div>
        </div>
        <div class="col-md-11">
            <p>{{ question.get_markdown|safe }}</p>
            <div class="question-user pull-right">
                <a href="{% url 'users:detail' question.user.username %}">{{ question.user.get_profile_name }} </a>
                <span class="text-secondary"> {{ question.created_at|naturaltime }}提问</span>
                {% if question.tags.names %}
                    {% for tag in question.tags.names %}
                        <span class="badge badge-primary">{{ tag }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <a href="{% url 'qa:propose_answer' question.id %}" class="btn btn-primary pull-right" role="button">提交回答</a>
    </div>
    <div class="page-header">
        <h1>回答</h1>
    </div>
    <div class="row">
        <ul class="col-md-12">
            {% for answer in question.answer_set.all %}
                {% include 'qa/answer_sample.html' with answer=answer %}
            {% empty %}
                <div class="text-center">
                    <h4>目前没有回答</h4>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}


{% block js %}
    <script src="{% static 'js/qa.js' %}" type="text/javascript"></script>
{% endblock js %}

wenhu/templates/qa/question_form.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}

{% block title %}提问 - {{ block.super }}{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'qa:all_q' %}">问答</a></li>
            <li class="breadcrumb-item active" aria-current="page">提问</li>
        </ol>
    </nav>
    <form action="{% url 'qa:ask_question' %}" enctype="multipart/form-data" id="question-form" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button id="publish" type="button" class="btn btn-primary">提交</button>
            <button id="draft" type="button" class="btn btn-default">保存草稿</button>
            <a class="btn btn-light" style="float:right" href="{% url 'qa:all_q' %}">取消</a>
        </div>
    </form>
    {{ form.media }}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/qa.js' %}"></script>
{% endblock js %}

wenhu/templates/qa/question_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}问答 - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'qa:unanswered_q' %}">问答</a></li>
        </ol>
    </nav>

    <div class="card my-4">
        <h5 class="card-header">按话题分类
            <a href="{% url 'qa:ask_question' %}" class="btn-sm btn-primary pull-right">
                <i class="fa fa-pencil" aria-hidden="true"></i> 提问
            </a>
        </h5>
        <div class="card-body">
            {% for tag, count in popular_tags %}
                <a href="#"><span class="badge badge-info">{{ count }} {{ tag }}</span></a>
            {% endfor %}
        </div>
    </div>
    <div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link{% if active == 'unanswered' %} active{% endif %}" href="{% url 'qa:unanswered_q' %}">
                    等待回答
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if active == 'answered' %} active{% endif %}" href="{% url 'qa:answered_q' %}">
                    已有回答
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if active == 'all' %} active{% endif %}" href="{% url 'qa:all_q' %}">
                    全部问答
                </a>
            </li>
        </ul>
        {% for question in questions %}
            {% include 'qa/question_sample.html' with question=question %}
        {% empty %}
            <h4 class="no-data">没有要显示的问题</h4>
        {% endfor %}

        {% if is_paginated %}
            <ul class="pagination justify-content-center mb-4">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">←上一页</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页→</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock content %}


{% block js %}
    <script src="{% static 'js/qa.js' %}"></script>
{% endblock js %}

wenhu/templates/qa/question_sample.html
{% load static humanize thumbnail %}

<div class="card questions">
    <div class="card-body">
        <div class="question-info pull-left text-center">
            <h3 class="{% if question.has_answer %}bg-success text-white{% endif %}">{{ question.count_answers }}</h3>
            <small class="text-secondary">回答</small>
            <h3>{{ question.total_votes }}</h3>
            <small class="text-secondary">投票</small>
        </div>
        <div>
            <h4 class="card-title">
                <a href="{% url 'qa:question_detail' question.pk %}">{{ question.title }}</a>
            </h4>
            <p>{{ question.get_markdown|safe|truncatechars:100 }}</p>
            <div class="question-user pull-right">
                <a href="{% url 'users:detail' question.user.username %}">{{ question.user.get_profile_name }} </a>
                <span class="text-secondary"> {{ question.created_at|naturaltime }}提问</span>
                {% if question.tags.names %}
                    {% for tag in question.tags.names %}
                        <span class="badge badge-primary"> {{ tag }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>